#!/bin/bash

VERSION=2.2.16
PACKAGE=aws-cli
TOOL=aws_completer
DIRECTORY=$(dirname $0)

STORAGES=(/ocean /bil /hive /local)

OPTIONS=""
for STORAGE in "${STORAGES[@]}"
do
	if [ -d "$STORAGE" ]; then
		OPTIONS=$OPTIONS" -B $STORAGE"
	fi
done

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"

